---
-
  hosts: osx
  gather_facts: no
  vars:
    user:
      name: stanaka
    rbenv:
      versions:
        - 2.4.0
        - 2.2.6
  vars_files:
    - vars.yml
  handlers:
    - include: handler.yml
  tasks:
    - include: tasks.yml
